On liq, assets must be repaid in order of borrow weight (decending)
solendprotocol/solana-program-library pull request #141
Opened 2023-04-12 14:48 UTC by 0xripleys

Title is self-explanatory. 

Motivation:
- borrow weights are generally correlated with riskiness, so we want to the risky assets repaid first.
- when we want to deprecate a reserve, the borrow weight will be cranked to infinity to remove all borrows of that asset. When that happens, we don't want other assets to be repaid. we only want the deprecated asset to be repaid across all obligations. 

Risk:
adding extra constraints on liquidations carries a bit of risk. If for whatever reason, the highest borrow weighted repay asset _can't_ be repaid on a specific obligation, then liquidations for that account are bricked which would be pretty bad.

However, https://github.com/solendprotocol/solana-program-library/pull/139 should address all cases related to liquidation failures so we shouldn't run into any issues here.

2023-04-12 20:28 UTC, 0xripleys commented on token-lending/program/src/processor.rs
> +                if borrow_reserve.borrow_weight() > cur_max_weight
if this was >=, the ordering of the borrows could change after every refresh_obligation call, which would be pretty bad.

2023-04-27 04:08 UTC, nope-finance commented on token-lending/program/src/processor.rs
> +            Some((cur_max_weight, _)) => {
stable order by 2nd order by pubkey (maybe in future we could use reserve util desc or total borrow value desc)

also maybe investigate if using borrow_weight() vs config.additional_borrow_weight makes a big difference in compute usage.

2023-04-27 04:11 UTC, nope-finance requested changes
see comment

2023-05-02 04:25 UTC, nope-finance approved these changes
good change

2023-05-04 03:47 UTC, merged