(WIP) Collateralization Limits Part 2
solendprotocol/solana-program-library pull request #172
Opened 2023-12-01 21:35 UTC by 0xripleys

2023-12-05 00:53 UTC, nope-finance requested changes

2023-12-05 00:53 UTC, nope-finance commented on token-lending/program/src/processor.rs
> +pub fn process_mark_obligation_as_closeable(
ig remove expiry time and change this to "set obligation close ability status"

2023-12-05 00:53 UTC, nope-finance commented on token-lending/program/src/processor.rs
> +    if obligation.is_closeable(clock.slot) && !any_borrow_attribution_limit_exceeded {
close vs open attribution limits

2023-12-05 00:53 UTC, nope-finance commented on token-lending/program/src/processor.rs
> +    if &lending_market.risk_authority != risk_authority_info.key {
or owner

2023-12-05 00:53 UTC, nope-finance commented on token-lending/sdk/src/state/reserve.rs
> +                return Ok(Decimal::zero());
i think gotta remove the protocol liquidation fee too

2023-12-06 19:44 UTC, 0xripleys commented
actually i don't think we need the init flag. the obligation collateral's borrow attribution value on upgrade will be zero, so the subtraction is useless anyways.

2023-12-08 21:00 UTC, nope-finance commented on token-lending/program/src/processor.rs
>          msg!("Lending market risk authority does not match the risk authority provided");
update msg

2023-12-08 21:04 UTC, nope-finance commented on token-lending/sdk/src/state/reserve.rs
> -    ) -> Result<Decimal, ProgramError> {
lets just return the protocol liquidation fee here and save self from re-serializing later

2023-12-16 23:19 UTC, merged